services:
  # 1. Base de Datos MySQL Unificada
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - notas_net

  # 2. Microservicio de Autenticación
  ms-auth:
    build: ./ms-auth
    container_name: ms-auth
    restart: always
    env_file:
      - .env
    environment:
      - PORT=${PORT_AUTH}
    depends_on:
      - mysql
    networks:
      - notas_net

  # 3. Microservicio de Usuarios
  ms-usuarios:
    build: ./ms-usuarios
    container_name: ms-usuarios
    restart: always
    env_file:
      - .env
    environment:
      - PORT=${PORT_USUARIOS}
    depends_on:
      - mysql
    networks:
      - notas_net

  # 4. Microservicio Académico
  ms-academico:
    build: ./ms-academico
    container_name: ms-academico
    restart: always
    env_file:
      - .env
    environment:
      - PORT=${PORT_ACADEMICO}
    depends_on:
      - mysql
    networks:
      - notas_net

  # 5. Microservicio de Notas
  ms-notas:
    build: ./ms-notas
    container_name: ms-notas
    restart: always
    env_file:
      - .env
    environment:
      - PORT=${PORT_NOTAS}
    depends_on:
      - mysql
    networks:
      - notas_net

  # 6. Microservicio de Soporte
  ms-soporte:
    build: ./ms-soporte
    container_name: ms-soporte
    restart: always
    env_file:
      - .env
    environment:
      - PORT=${PORT_SOPORTE}
    depends_on:
      - mysql
    networks:
      - notas_net

  # 7. API Gateway
  ms-gateway:
    build: ./ms-gateway
    container_name: ms-gateway
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT_GATEWAY}:8080"
    environment:
      - PORT=8080
      - MS_AUTH_URL=http://ms-auth:${PORT_AUTH}
      - MS_USUARIOS_URL=http://ms-usuarios:${PORT_USUARIOS}
      - MS_ACADEMICO_URL=http://ms-academico:${PORT_ACADEMICO}
      - MS_NOTAS_URL=http://ms-notas:${PORT_NOTAS}
      - MS_SOPORTE_URL=http://ms-soporte:${PORT_SOPORTE}
    depends_on:
      - ms-auth
      - ms-usuarios
      - ms-academico
      - ms-notas
      - ms-soporte
    networks:
      - notas_net

  # 8. Servidor Frontend (Nginx)
  ms-frontend:
    build: ./ms-frontend
    container_name: ms-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - ms-gateway
    networks:
      - notas_net

volumes:
  mysql_data:
    name: portal_notas_mysql_data

networks:
  notas_net:
    driver: bridge